version: 2
models:
  - name: dim_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]
  - name: dim_products
    columns:
      - name: product_id
        tests: [not_null, unique]
  - name: dim_dates
    columns:
      - name: date
        tests: [not_null, unique]
  - name: fct_order_items
    columns:
      - name: order_item_id
        tests: [not_null, unique]
      - name: customer_id
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_id
      - name: product_id
        tests:
          - relationships:
              to: ref('dim_products')
              field: product_id
      - name: order_date
        tests:
          - relationships:
              to: ref('dim_dates')
              field: date
